### ISSUE TITLE
What's the electron-open method return?

### ISSUE THREAD

**Issue by wufeng87** [rhysd/electron-open-url#5]
I want to open electron app in nodejs server, and The nodejs server process should be comunicate with the electron app process.
Best Regards!

**Comment by rhysd** [comment]
As [source](https://github.com/rhysd/electron-open-url/blob/master/index.js) says, it returns nothing. What do you expect for returned value?

**Comment by wufeng87** [comment]
I need to send message from nodejs server process to electron process. I wonder how could I do it?

**Comment by wufeng87** [comment]
I should try use WebSocket instead.
